version: '3.4'

services:
  whatsinthephotoapi:
    image: ${DOCKER_REGISTRY-}whatsinthephotoapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    links:
      - ${DOCKER_REGISTRY-}whatsinthephotoapi
    environment:
      - DOMAIN=whatsinthephotoapi
      - PORT=8080